# Generated by Django 5.2.2 on 2025-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination'), ('event', 'School Event'), ('break', 'School Break')], max_length=50)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('high', 'High School')], max_length=20)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('curriculum', models.TextField(help_text='Curriculum overview')),
                ('requirements', models.TextField(blank=True, help_text='Admission requirements')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['program_type', 'name'],
            },
        ),
    ]
