# Generated by Django 5.2.2 on 2025-12-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['level', 'name']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level'), ('ordinaryadvanced', 'Ordinary and Advanced Levels')], default='ordinary', max_length=20),
        ),
    ]
