# Generated by Django 5.2.2 on 2025-12-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_options_remove_subject_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level')], max_length=20),
        ),
    ]
