# Generated by Django 5.2.2 on 2025-12-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='head_teacher_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
