# Generated by Django 5.2.2 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('head', 'Head Teacher'), ('deputy1', 'Deputy Head Teacher Administaration'), ('deputy', 'Deputy Head Teacher Academics'), ('dos', 'Director of Studies'), ('sec', 'Secretary'), ('teacher', 'Teacher'), ('support', 'Support Staff')], max_length=20),
        ),
    ]
