# Generated by Django 5.2.2 on 2025-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_description', models.TextField(help_text='Description displayed in the footer')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL', null=True)),
                ('school_hours_weekdays', models.CharField(default='Monday - Friday: 8:00 AM - 3:00 PM', help_text='Weekday hours (e.g., Monday - Friday: 8:00 AM - 3:00 PM)', max_length=100)),
                ('school_hours_saturday', models.CharField(default='Saturday: 9:00 AM - 12:00 PM', help_text='Saturday hours', max_length=100)),
                ('school_hours_sunday', models.CharField(default='Sunday: Closed', help_text='Sunday hours', max_length=100)),
                ('copyright_text', models.CharField(default='© 2024 Our School. All rights reserved.', help_text='Copyright text displayed in footer', max_length=200)),
                ('privacy_policy_url', models.URLField(blank=True, help_text='Privacy Policy page URL', null=True)),
                ('terms_of_service_url', models.URLField(blank=True, help_text='Terms of Service page URL', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
